export { default as ExpertisePharma } from './expertise/ExpertisePharma'
export { default as ExpertiseQuality } from './expertise/ExpertiseQuality'
export { default as Contact } from './contact/Contact'
export { default as Home } from './home/Home'
export { default as Leadership } from './leadership/Leadership'
export { default as Insight } from './insight/Insight'
export { default as About } from './about/About'
export { default as Dashboard } from './dashboard/Dashboard'
